language: generic

sudo: required
services: docker

# Avoid timestamping issues
before_script:
  - find . -name \*.info -exec touch '{}' \;
  - touch ./source/texk/web2c/web2c/web2c-lexer.c
  - touch ./source/texk/web2c/web2c/web2c-parser.c
  - touch ./source/texk/web2c/web2c/web2c-parser.h

env:
  global:
    - JOBS_IF_PARALLEL=2

matrix:
  include:
    - os: linux
      services: docker
      env: package=luatex-bin-x86_64-musl.tar.gz
      script: docker run -e JOBS_IF_PARALLEL="${JOBS_IF_PARALLEL}" -v ${TRAVIS_BUILD_DIR}:/luatex -w /luatex -it alpine:3.1 sh -c "apk update; apk add --no-progress bash gcc g++ make; ./build.sh --parallel --jit"

before_deploy:
  - if [ -n "$package" ]; then tar czvf ${package} -C build/texk/web2c luajittex luatex ; fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $package
  skip_cleanup: true
  on:
    tags: true
    condition: $package != ""
